### PR TITLE
Conversion of mruby-zest and osc-bridge to git-subrepo

### PR DESCRIPTION
**Pull request by pgervais**
This PR replaces the mruby-zest and osc-bridge submodules by a git-subrepo equivalent. All the commits have been obtained using a bash script shown below. Note that it brings in the latest version of mruby-zest as well.

CAVEAT: anybody who has a checked-out version of mruby-zest-build with submodules initialized and updated won't be able to "git pull" through those commits without manually deleting src/osc-bridge and src/mruby-zest prior to it. An alternative solution is to start from a fresh repository clone.

So the upgrade path is something like:

```
git fetch
git checkout master
rm -rf src/mruby-zest src/osc-bridge
git pull
```

Script used to generate this PR, to be run in the parent directory of mruby-zest-build/. Requires an install of git-subrepo. It can be easily adapted to convert any other submodule:

```
DIRECTORY=mruby-zest-build

function submodule_to_subrepo() {    
    git config -f .gitmodules --remove-section submodule.${SUBMODULE_SECTION}
    git add .gitmodules
    git config --local --remove-section submodule.${SUBMODULE_SECTION}
    git rm --cached ${SUBMODULE_PATH}
    rm -rf .git/modules/${SUBMODULE_SECTION}
    git commit -m "Deleted ${SUBMODULE_PATH} submodule"
    rm -rf ${SUBMODULE_PATH}
    git subrepo clone ${SUBMODULE_URL} ${SUBMODULE_PATH}
}

pushd ${DIRECTORY}
git checkout -b git-subrepo

SUBMODULE_PATH=src/mruby-zest
SUBMODULE_NAME=mruby-zest
SUBMODULE_URL=git@github.com:mruby-zest/mruby-zest.git
SUBMODULE_SECTION=${SUBMODULE_PATH}
submodule_to_subrepo
    
SUBMODULE_PATH=src/osc-bridge
SUBMODULE_NAME=osc-bridge
SUBMODULE_URL=git@github.com:mruby-zest/osc-bridge.git
SUBMODULE_SECTION=deps/osc-bridge

submodule_to_subrepo
popd
```

### CODE REVIEW

**Comment by pgervais** [comment]
Now that I think of it, a way to avoid having to rm -rf the existing code under src/mruby-zest and src/osc-bridge would be to have the git subrepos under a different directory (e.g. subrepos/ or something along those lines). If you prefer this solution, I'll put together another PR.

**Comment by pgervais** [comment]
Friend ping, I am (maybe needlessly) waiting for this PR to be merged to continue fixing UI issue with Zynfusion. When can I hope to have a decision made on this PR? 
Thanks

**Comment by fundamental** [comment]
Thanks for the reminder ping. I've been a bit overly absorbed with a DIY electronics synth project of mine (~40 hr project according to the build instructions if you have more of an idea what you're doing). I keep saying "I'm almost ready to test the physical transistor ladder filter" time and time again before finding more pages of instructions to go through. Whenever I hit that point I get to also review one of the software ladder filter PRs :). In order to make better progress with zyn and other DIY projects I've got a few larger chunks of time lined up. 

I should be able to have this PR either updated or merged in by the end of this next weekend. Ideally before this weekend, but I know how that optimism tends to go...

**Comment by fundamental** [comment]
I'll fire off an email off to the mailing list to let people know about this merge as there's the repo update issue you've mentioned. There's also at least one PR open on one of the subrepos, so I've installed the commands, read through some docs and I think I should be able to bumble my way through synchronization as a result of some of the reading. Thanks for bearing with the delays and thanks a ton for taking care of this big step forward in terms of simplifying contributions :+1:

**Pull request merged**
