### PR TITLE
improve LFO layout for readability

### PR DESCRIPTION
**Pull request by friedolino78**

### CODE REVIEW

**Comment by fundamental** [comment]
Thanks. I'll target taking a look at this PR Friday evening.

**Comment by fundamental** [comment]
Looks like a solid improvement. I think it would be nice to get the sine/sync/tempo to be vertically centered, so I might take a look at that tomorrow before merging (I forget if the centering is a one liner or not). As mentioned on IRC, ideally there's more of a "this LFO is in a BPM based mode" which causes additional controls to appear/disappear, but this PR does move things in the right direction.

**Comment by friedolino78** [comment]
> As mentioned on IRC, ideally there's more of a "this LFO is in a BPM based mode" which causes additional controls to appear/disappear

now freq knob gets disabled if lfo is running in bpm sync.

**Comment by fundamental** [comment]
Still feels clunky, but things are certainly readable with the modification, so a step in the right _sequence_ :+1:

**Pull request merged**
