### PR TITLE
Pull libuv 1.40.0 as a submodule

### PR DESCRIPTION
**Pull request by pgervais**
Here's another proposal to simplify things a bit, by using submodule to pull in libuv, instead of using the published tarball.

Caveats:
- this change also upgrades libuv from 1.9.1 to 1.40.0. I only tested it (lightly) on Linux. A lower-risk change would be to keep the version the same, it's straightforward to do.
- there must have been a good reason to use the tarball version instead of a submodule, which I lack the context for. Happy to update this PR accordingly.

### CODE REVIEW

**Comment by fundamental** [comment]
I'm somewhat torn on this one. Ideally we should be moving to not have libuv built as part of the process on linux and just link with the dynamic lib there. There's no dependency on any particular version of libuv, so there's no explicit need to have a vendored version of it floating around. Annoyingly some linux distros have broken static libs for libuv in their packaged version (I think someone forgot a -fPIC), which complicates things somewhat. Windows it still needs to be built along the way to obtain a zero dependency binary...

**Comment by pgervais** [comment]
Makes sense, I can look into using the distro version (the dynamic one) on Linux instead. I currently don't have access to a windows or a mac machine so I'll leave both untouched in the Makefile.

But if you believe strongly that libuv should be statically linked on Linux too, and the static version is broken on some distros, then I don't see many other solutions than vendoring it.

I'll follow what you decide.

**Comment by fundamental** [comment]
I'm 100% fine with dynamic linking to libuv on Linux.

I don't have access to either a windows or mac machine either, which has made a good bit of development 'interesting'...
Windows builds happen with mingw which used to be done on a ubuntu VM. The VM broke a million times, so now it's mingw within a docker instance.

**Comment by pgervais** [comment]
I've updated the linux build to use the system libuv instead of the vendored version, and left both the windows and mac builds unchanged (that is, using libuv 1.40.0 from the submodule).

What do you think?

**Comment by fundamental** [comment]
Looks good for the most part. There was a small typo in the README and it looked to me like the windows cross build could trigger both windows mode and linux mode at the same time. I fixed both while merging as that seemed like the easiest way.

Thanks for the enhancement :)

**Comment by pgervais** [comment]
Mark, I remember reading somewhere else that you were considering merging some dependencies currently pulled as submodules into mruby-zest-build itself. Happy to help with that. 
In particular, merging mruby-zest would simplify things quite a bit.

What do you think? Happy to follow any proposal that you already have written somewhere, or happy to write one if you think that's useful.

**Comment by fundamental** [comment]
The plans were:

- merge PUGL directly in and strip it down throwing out git history (partially done already)
- merge mruby-zest directly in keeping history with https://github.com/ingydotnet/git-subrepo
- merge osc-bridge directly in keeping history with https://github.com/ingydotnet/git-subrepo

mruby-qml-parse and mruby-qml-spawn have exceptionally rare modifications at this point, so they likely can stay as they are.

I haven't worked extensively with git-subrepo, but if you want to approach that then the assistance is very much welcome. I'd imagine it's going to be a pretty big merge. I'm guessing a writeup of "run these commands and everything looks right" will be easier to review than the massive PR that it would create.

Merging those two will take the addition of a new parameter on zyn's side down from 4 commits in 4 repositories down to just 2 commits (one on the backend, one on the GUI), so it would be a good quality of life improvement.

**Comment by pgervais** [comment]
Great, I'll take a stab at mruby-zest and osc-bridge with git-subrepo next week then.

**Comment by pgervais** [comment]
PR converting submodules to git-subrepo: https://github.com/mruby-zest/mruby-zest-build/pull/41

**Pull request merged**
