### PR TITLE
Comb filter

### PR DESCRIPTION
**Pull request by friedolino78**
gui for https://github.com/zynaddsubfx/zynaddsubfx/pull/126

### CODE REVIEW

**Comment by fundamental** [comment]
Looks like b6423ba is unrelated to the goal of this PR.

**Comment by friedolino78** [comment]
> Looks like [b6423ba](https://github.com/mruby-zest/mruby-zest-build/commit/b6423ba9a2e2b84dc83c7c0731ff21a4022985fa) is unrelated to the goal of this PR.

i need the numedit changes. 
the migration from mruby-zest to mruby-zest-build repo seems to make strange things to my file organisation.

**Comment by friedolino78** [comment]
did some rebase to filter out the totally unrelated files.

**Comment by fundamental** [comment]
The .qml changes look 100% fine to me. The OSC schema changes appear to incorporate changes for the repeating envelopes, lfo fade out, and a few other pieces. Fairly minor issue given that those other PRs appear to be progressing along fine. This PR should be fine to merge once the zyn side is in.

**Comment by friedolino78** [comment]
> The .qml changes look 100% fine to me. The OSC schema changes appear to incorporate changes for the repeating envelopes, lfo fade out, and a few other pieces. Fairly minor issue given that those other PRs appear to be progressing along fine. This PR should be fine to merge once the zyn side is in.

after more rebasing most of the bycatch in OSC schema is gone. only a small change in denominator range for bpm handling is in there that should have been in the bpmSyncInternal commit.

**Comment by fundamental** [comment]
Looks good to merge to me :+1:

**Pull request merged**
